// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RemoteGeometryClient is the client API for RemoteGeometry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteGeometryClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Sends another greeting
	SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	CreateSheetCircle(ctx context.Context, in *CreateSheetCircleRequest, opts ...grpc.CallOption) (*ObjectID, error)
}

type remoteGeometryClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteGeometryClient(cc grpc.ClientConnInterface) RemoteGeometryClient {
	return &remoteGeometryClient{cc}
}

func (c *remoteGeometryClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/RemoteGeometry/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteGeometryClient) SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/RemoteGeometry/SayHelloAgain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteGeometryClient) CreateSheetCircle(ctx context.Context, in *CreateSheetCircleRequest, opts ...grpc.CallOption) (*ObjectID, error) {
	out := new(ObjectID)
	err := c.cc.Invoke(ctx, "/RemoteGeometry/CreateSheetCircle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteGeometryServer is the server API for RemoteGeometry service.
// All implementations must embed UnimplementedRemoteGeometryServer
// for forward compatibility
type RemoteGeometryServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Sends another greeting
	SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error)
	CreateSheetCircle(context.Context, *CreateSheetCircleRequest) (*ObjectID, error)
	mustEmbedUnimplementedRemoteGeometryServer()
}

// UnimplementedRemoteGeometryServer must be embedded to have forward compatible implementations.
type UnimplementedRemoteGeometryServer struct {
}

func (UnimplementedRemoteGeometryServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedRemoteGeometryServer) SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloAgain not implemented")
}
func (UnimplementedRemoteGeometryServer) CreateSheetCircle(context.Context, *CreateSheetCircleRequest) (*ObjectID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSheetCircle not implemented")
}
func (UnimplementedRemoteGeometryServer) mustEmbedUnimplementedRemoteGeometryServer() {}

// UnsafeRemoteGeometryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteGeometryServer will
// result in compilation errors.
type UnsafeRemoteGeometryServer interface {
	mustEmbedUnimplementedRemoteGeometryServer()
}

func RegisterRemoteGeometryServer(s grpc.ServiceRegistrar, srv RemoteGeometryServer) {
	s.RegisterService(&RemoteGeometry_ServiceDesc, srv)
}

func _RemoteGeometry_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteGeometryServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteGeometry/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteGeometryServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteGeometry_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteGeometryServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteGeometry/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteGeometryServer).SayHelloAgain(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteGeometry_CreateSheetCircle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSheetCircleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteGeometryServer).CreateSheetCircle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteGeometry/CreateSheetCircle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteGeometryServer).CreateSheetCircle(ctx, req.(*CreateSheetCircleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteGeometry_ServiceDesc is the grpc.ServiceDesc for RemoteGeometry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteGeometry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RemoteGeometry",
	HandlerType: (*RemoteGeometryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _RemoteGeometry_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _RemoteGeometry_SayHelloAgain_Handler,
		},
		{
			MethodName: "CreateSheetCircle",
			Handler:    _RemoteGeometry_CreateSheetCircle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
